/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visual;

/**
 *
 * @author Jhon fonseca
 */
import java.util.ArrayList;
import Lista.Listavehiculo;
import javax.swing.JOptionPane;

public class JInternalFrameRegistrodeVehiculos extends javax.swing.JInternalFrame {

    ArrayList<Listavehiculo> DescripcionVehiculo = new ArrayList<>();

    /**
     * Creates new form JInternalFrameRegistrodeVehiculos
     */
    public JInternalFrameRegistrodeVehiculos() {
        initComponents();

    }

    public void LimpiarCampos() {
        this.jTextFieldNombre.setText("");
        this.jTextFieldPlaca.setText("");
        this.jTextFieldColor.setText("");
        this.jTextFieldKilometraje.setText("");
        this.jTextFieldModelo.setText("");
        this.jTextFieldAño.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelGasolina = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonActualizar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabelDueño = new javax.swing.JLabel();
        jComboBoxSituacion = new javax.swing.JComboBox<>();
        jLabelTipo = new javax.swing.JLabel();
        jLabelSituacion = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jLabelAño = new javax.swing.JLabel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxGasolina = new javax.swing.JComboBox<>();
        jLabelKilom = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jTextFieldColor = new javax.swing.JTextField();
        jTextFieldKilometraje = new javax.swing.JTextField();
        jTextFieldAño = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jCheckBoxTricop = new javax.swing.JCheckBox();
        jCheckBoxEspIz = new javax.swing.JCheckBox();
        jCheckBoxEspD = new javax.swing.JCheckBox();
        jLabelCodigo2 = new javax.swing.JLabel();
        jCheckBoxUnidadL = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jCheckBoxEncendedor = new javax.swing.JCheckBox();
        jCheckBoxEspejoR = new javax.swing.JCheckBox();
        jCheckBoxbocina = new javax.swing.JCheckBox();
        jCheckBoxAlfom = new javax.swing.JCheckBox();
        jLabelCodigo5 = new javax.swing.JLabel();
        jCheckBoxRadio = new javax.swing.JCheckBox();
        jCheckBoxForros = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jCheckBoxExtintor = new javax.swing.JCheckBox();
        jCheckBoxLlanta = new javax.swing.JCheckBox();
        jCheckBoxManeralG = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jLabelCodigo6 = new javax.swing.JLabel();
        jCheckBoxGata = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jCheckBoxOtros = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBoxSeguro = new javax.swing.JCheckBox();
        jCheckBoxEmicionG = new javax.swing.JCheckBox();
        jLabelCodigo7 = new javax.swing.JLabel();
        jCheckBoxCirculacion = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGasolina.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelGasolina.setText("Gasolina:");
        jPanel1.add(jLabelGasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 100, 20));

        jLabelPlaca.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelPlaca.setText("Placa:");
        jPanel1.add(jLabelPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 50, 20));
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, -1));

        jButtonActualizar.setBackground(new java.awt.Color(51, 153, 0));
        jButtonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizar.setText("Actualizar");
        jPanel1.add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        jButtonGuardar.setBackground(new java.awt.Color(51, 153, 0));
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        jButtonEliminar.setBackground(new java.awt.Color(255, 0, 51));
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar");
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Usuario");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vehiculo");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Obregon");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mecanica");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel5.setText("Garantia");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jButton5.setBackground(new java.awt.Color(51, 51, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Cerrar");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 50, 50));

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setText("Reporte y");
        jButton3.setBorder(null);
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("   Registrar");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 70, 50));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Añadir");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 40));

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setText("Crear cliente");
        jButton4.setBorder(null);
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, 50));

        jButton6.setBackground(new java.awt.Color(51, 51, 255));
        jButton6.setText("Dianostico");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 50));

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carrro ", "Camion", "Camioneta" }));
        jPanel1.add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabelDueño.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelDueño.setText("Nombre:");
        jPanel1.add(jLabelDueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 20));

        jComboBoxSituacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diagnostico", "Cambio de aceite", "Cambio de correa" }));
        jPanel1.add(jComboBoxSituacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 100, -1));

        jLabelTipo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelTipo.setText("Tipo:");
        jPanel1.add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 50, 20));

        jLabelSituacion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelSituacion.setText("Situación:");
        jPanel1.add(jLabelSituacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 100, 20));

        jLabelColor.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelColor.setText("Color:");
        jPanel1.add(jLabelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 60, 20));

        jLabelAño.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelAño.setText("Año:");
        jPanel1.add(jLabelAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 50, 20));
        jPanel1.add(jTextFieldPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jComboBoxGasolina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "20", "40", "50", "70", "80", "90", "100" }));

        jLabelKilom.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelKilom.setText("Kilometraje:");

        jLabelModelo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelModelo.setText("Modelo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTextFieldAño))
                .addGap(38, 38, 38)
                .addComponent(jLabelKilom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxGasolina, 0, 100, Short.MAX_VALUE)
                    .addComponent(jTextFieldKilometraje))
                .addGap(100, 100, 100))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jComboBoxGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelKilom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 720, 140));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jCheckBoxTricop.setText(" Tricot");
        jCheckBoxTricop.setContentAreaFilled(false);

        jCheckBoxEspIz.setText("Espejo Izquierdo");
        jCheckBoxEspIz.setContentAreaFilled(false);

        jCheckBoxEspD.setText("Espejo derecho");
        jCheckBoxEspD.setContentAreaFilled(false);

        jLabelCodigo2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelCodigo2.setText("Exteriores");

        jCheckBoxUnidadL.setText("Unidad de luces");
        jCheckBoxUnidadL.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodigo2)
                    .addComponent(jCheckBoxEspIz)
                    .addComponent(jCheckBoxEspD)
                    .addComponent(jCheckBoxUnidadL)
                    .addComponent(jCheckBoxTricop))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabelCodigo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxUnidadL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEspD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEspIz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTricop)
                .addGap(72, 72, 72))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 180, 210));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jCheckBoxEncendedor.setText("Encendedor");
        jCheckBoxEncendedor.setContentAreaFilled(false);

        jCheckBoxEspejoR.setText("Espejo retrovisor");
        jCheckBoxEspejoR.setContentAreaFilled(false);

        jCheckBoxbocina.setText("Bocina");
        jCheckBoxbocina.setContentAreaFilled(false);

        jCheckBoxAlfom.setText("Alfombra");
        jCheckBoxAlfom.setContentAreaFilled(false);

        jLabelCodigo5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelCodigo5.setText("Interiores");

        jCheckBoxRadio.setText("Radio");
        jCheckBoxRadio.setContentAreaFilled(false);

        jCheckBoxForros.setText("Forros de hacientos");
        jCheckBoxForros.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodigo5)
                    .addComponent(jCheckBoxEspejoR)
                    .addComponent(jCheckBoxbocina)
                    .addComponent(jCheckBoxRadio)
                    .addComponent(jCheckBoxAlfom)
                    .addComponent(jCheckBoxEncendedor)
                    .addComponent(jCheckBoxForros))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabelCodigo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxbocina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEspejoR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAlfom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEncendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxForros)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 190, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jCheckBoxExtintor.setText("Exstintor");
        jCheckBoxExtintor.setContentAreaFilled(false);

        jCheckBoxLlanta.setText("Triangulo");
        jCheckBoxLlanta.setContentAreaFilled(false);

        jCheckBoxManeralG.setText("Maneral de gata");
        jCheckBoxManeralG.setContentAreaFilled(false);

        jCheckBox29.setText("Llanta");
        jCheckBox29.setContentAreaFilled(false);

        jLabelCodigo6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelCodigo6.setText("Accesorio");

        jCheckBoxGata.setText("Gata");
        jCheckBoxGata.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodigo6)
                    .addComponent(jCheckBoxLlanta)
                    .addComponent(jCheckBoxManeralG)
                    .addComponent(jCheckBoxGata)
                    .addComponent(jCheckBox29)
                    .addComponent(jCheckBoxExtintor))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabelCodigo6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxGata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxManeralG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxLlanta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxExtintor)
                .addGap(46, 46, 46))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 170, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jCheckBoxOtros.setText("Otros");
        jCheckBoxOtros.setContentAreaFilled(false);

        jCheckBox31.setText("Chequeo mecanico");
        jCheckBox31.setContentAreaFilled(false);

        jCheckBoxSeguro.setText("Seguro");
        jCheckBoxSeguro.setContentAreaFilled(false);

        jCheckBoxEmicionG.setText("Emicion de gas");
        jCheckBoxEmicionG.setContentAreaFilled(false);
        jCheckBoxEmicionG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEmicionGActionPerformed(evt);
            }
        });

        jLabelCodigo7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelCodigo7.setText("Documentos");

        jCheckBoxCirculacion.setText("Circulacion");
        jCheckBoxCirculacion.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodigo7)
                    .addComponent(jCheckBox31)
                    .addComponent(jCheckBoxSeguro)
                    .addComponent(jCheckBoxCirculacion)
                    .addComponent(jCheckBoxEmicionG)
                    .addComponent(jCheckBoxOtros))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabelCodigo7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxCirculacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxSeguro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEmicionG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxOtros)
                .addGap(46, 46, 46))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
    
        try {

            String NombreV = jTextFieldNombre.getText().trim();
            String PlacaV = jTextFieldPlaca.getText().trim();
            String ModeloV = jTextFieldModelo.getText().trim();
            String TipoV = jComboBoxTipo.getSelectedItem().toString();
            String SituacionV = jComboBoxSituacion.getSelectedItem().toString();
            String ColorV = jTextFieldColor.getText().trim();
            String AñoV = jTextFieldAño.getText().trim();
            String GasolinaV = jComboBoxGasolina.getSelectedItem().toString();
            String kilometrajeV = jTextFieldKilometraje.getText().trim();
            if (NombreV.isEmpty() || PlacaV.isEmpty() || ModeloV.isEmpty() || TipoV.isEmpty()
                    || SituacionV.isEmpty() || ColorV.isEmpty() || AñoV.isEmpty() || GasolinaV.isEmpty() || kilometrajeV.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Complete todos los campos");
            
            return;
        }
        
        Listavehiculo e = new Listavehiculo(NombreV, PlacaV, ModeloV, TipoV, SituacionV, ColorV, AñoV, GasolinaV, kilometrajeV);
        DescripcionVehiculo.add(e);
        
        JOptionPane.showMessageDialog(null, "Se ha agregado correctamente");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error al guardar");
    }//GEN-LAST:event_jButtonGuardarActionPerformed
    }
    private void jCheckBoxEmicionGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEmicionGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEmicionGActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        LimpiarCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBoxAlfom;
    private javax.swing.JCheckBox jCheckBoxCirculacion;
    private javax.swing.JCheckBox jCheckBoxEmicionG;
    private javax.swing.JCheckBox jCheckBoxEncendedor;
    private javax.swing.JCheckBox jCheckBoxEspD;
    private javax.swing.JCheckBox jCheckBoxEspIz;
    private javax.swing.JCheckBox jCheckBoxEspejoR;
    private javax.swing.JCheckBox jCheckBoxExtintor;
    private javax.swing.JCheckBox jCheckBoxForros;
    private javax.swing.JCheckBox jCheckBoxGata;
    private javax.swing.JCheckBox jCheckBoxLlanta;
    private javax.swing.JCheckBox jCheckBoxManeralG;
    private javax.swing.JCheckBox jCheckBoxOtros;
    private javax.swing.JCheckBox jCheckBoxRadio;
    private javax.swing.JCheckBox jCheckBoxSeguro;
    private javax.swing.JCheckBox jCheckBoxTricop;
    private javax.swing.JCheckBox jCheckBoxUnidadL;
    private javax.swing.JCheckBox jCheckBoxbocina;
    private javax.swing.JComboBox<String> jComboBoxGasolina;
    private javax.swing.JComboBox<String> jComboBoxSituacion;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAño;
    private javax.swing.JLabel jLabelCodigo2;
    private javax.swing.JLabel jLabelCodigo5;
    private javax.swing.JLabel jLabelCodigo6;
    private javax.swing.JLabel jLabelCodigo7;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelDueño;
    private javax.swing.JLabel jLabelGasolina;
    private javax.swing.JLabel jLabelKilom;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelSituacion;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextFieldAño;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldKilometraje;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPlaca;
    // End of variables declaration//GEN-END:variables
}
