/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Visual;

/**
 *
 * @author Jhon fonseca
 */
public class MDIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MDIPrincipal
     */
    public MDIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu2 = new javax.swing.JMenu();
        RegistrarVehiculoMenuItem2 = new javax.swing.JMenuItem();
        DiagnosticoMenuItem2 = new javax.swing.JMenuItem();
        AñadirUsuarioMenuItem2 = new javax.swing.JMenuItem();
        exitMenuItem2 = new javax.swing.JMenuItem();
        fileMenu = new javax.swing.JMenu();
        RegistrarVehiculoMenuItem = new javax.swing.JMenuItem();
        DiagnosticoMenuItem = new javax.swing.JMenuItem();
        AñadirUsuarioMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu2.setMnemonic('f');
        fileMenu2.setText("Inicio");

        RegistrarVehiculoMenuItem2.setMnemonic('o');
        RegistrarVehiculoMenuItem2.setText("Inicion de seccion");
        RegistrarVehiculoMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarVehiculoMenuItem2ActionPerformed(evt);
            }
        });
        fileMenu2.add(RegistrarVehiculoMenuItem2);

        DiagnosticoMenuItem2.setMnemonic('s');
        DiagnosticoMenuItem2.setText("Crear Cuenta");
        DiagnosticoMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiagnosticoMenuItem2ActionPerformed(evt);
            }
        });
        fileMenu2.add(DiagnosticoMenuItem2);

        AñadirUsuarioMenuItem2.setMnemonic('a');
        AñadirUsuarioMenuItem2.setText("Reporte y garantia");
        fileMenu2.add(AñadirUsuarioMenuItem2);

        exitMenuItem2.setMnemonic('x');
        exitMenuItem2.setText("Exit");
        exitMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem2ActionPerformed(evt);
            }
        });
        fileMenu2.add(exitMenuItem2);

        menuBar.add(fileMenu2);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Empleado");

        RegistrarVehiculoMenuItem.setMnemonic('o');
        RegistrarVehiculoMenuItem.setText("Registro de Vehiculo");
        RegistrarVehiculoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarVehiculoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(RegistrarVehiculoMenuItem);

        DiagnosticoMenuItem.setMnemonic('s');
        DiagnosticoMenuItem.setText("Diagnostico");
        DiagnosticoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiagnosticoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(DiagnosticoMenuItem);

        AñadirUsuarioMenuItem.setMnemonic('a');
        AñadirUsuarioMenuItem.setText("Añadir Usuario");
        fileMenu.add(AñadirUsuarioMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void RegistrarVehiculoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarVehiculoMenuItemActionPerformed
JInternalFrameRegistrodeVehiculos RegistrodeVehiculo =new JInternalFrameRegistrodeVehiculos();
desktopPane.add(RegistrodeVehiculo);
RegistrodeVehiculo.show();

// Para visualizar la ventana de diagnostico
    }//GEN-LAST:event_RegistrarVehiculoMenuItemActionPerformed

    private void DiagnosticoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiagnosticoMenuItemActionPerformed
      JInternalFrameDiagnostico Diagnostico =new JInternalFrameDiagnostico();
desktopPane.add(Diagnostico);
Diagnostico.show();  // TODO add your handling code here:
    }//GEN-LAST:event_DiagnosticoMenuItemActionPerformed

    private void RegistrarVehiculoMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarVehiculoMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarVehiculoMenuItem2ActionPerformed

    private void DiagnosticoMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiagnosticoMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiagnosticoMenuItem2ActionPerformed

    private void exitMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AñadirUsuarioMenuItem;
    private javax.swing.JMenuItem AñadirUsuarioMenuItem2;
    private javax.swing.JMenuItem DiagnosticoMenuItem;
    private javax.swing.JMenuItem DiagnosticoMenuItem2;
    private javax.swing.JMenuItem RegistrarVehiculoMenuItem;
    private javax.swing.JMenuItem RegistrarVehiculoMenuItem2;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exitMenuItem2;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu fileMenu2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
